version: 2

sources:
   - name: facebook_ads
     database: postgres # adjust if needed
     schema: facebook_ads
     tables:
        - name: test_facebook_ads
          columns:
             - name: campaign_id
               description: Unique identifier for the campaign
             - name: date
               description: Date of the metrics
             - name: account_id
               description: Facebook Ads account identifier
             - name: clicks
               description: Number of clicks
             - name: impressions
               description: Number of impressions
             - name: spend
               description: Amount spent in campaign currency
             - name: campaign_name
               description: Name of the campaign

   - name: google_ads
     database: postgres # adjust if needed
     schema: test_googleads_schema
     tables:
        - name: test_googleads_campaings
          columns:
             - name: id
               description: Unique identifier for the campaign
             - name: date
               description: Date of the metrics
             - name: customer_id
               description: Google Ads customer identifier
             - name: clicks
               description: Number of clicks
             - name: impressions
               description: Number of impressions
             - name: cost_micros
               description: Cost in millionths of the account currency
             - name: name
               description: Name of the campaign
